{
 "title": "Celery Monitoring",
 "description": "Monitor Celery Tasks with Prometheus and celery-exporter",
 "tags": [
  "prometheus",
  "celery"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Celery Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Celery Events by State rate (average 5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(celery_tasks_total[5m])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Celery Events by Tasks rate (average 5m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(celery_tasks_total[5m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Celery Tasks runtime rate (average 5m)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg(rate(celery_tasks_runtime_seconds_bucket[5m]))",
     "legendFormat": "{{rt}}"
    }
   ]
  },
  {
   "title": "Celery Task latency rate (by 5m)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg(rate(celery_tasks_latency_seconds_bucket[5m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Current Worker Count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "celery_workers" }
   ]
  },
  { "title": "Top Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Top 15 Tasks Started",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(celery_tasks_total{state=\"STARTED\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 15 Tasks Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(celery_tasks_total{state=\"SUCCESS\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 15 Tasks FAILED",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
   "repeat": "State",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(celery_tasks_total{state=\"FAILURE\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 15 Tasks RETRY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(celery_tasks_total{state=\"RETRY\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}